// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "description": "Email ve şifre ile kullanıcı girişi yapılır",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Kullanıcı girişi",
                "parameters": [
                    {
                        "description": "Giriş bilgileri",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/polyclinics": {
            "get": {
                "description": "Sistemdeki tüm poliklinikleri listeler.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Polyclinic"
                ],
                "summary": "Tüm poliklinikleri getir",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Polyclinic"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Yeni bir poliklinik ekler.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Polyclinic"
                ],
                "summary": "Yeni poliklinik oluştur",
                "parameters": [
                    {
                        "description": "Poliklinik verisi",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Polyclinic"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/polyclinics/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Polyclinic"
                ],
                "summary": "Poliklinik bilgilerini güncelle",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Poliklinik ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Yeni poliklinik verisi",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Polyclinic"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "ID'ye göre poliklinik kaydını siler.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Polyclinic"
                ],
                "summary": "Poliklinik sil",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Poliklinik ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Yeni kullanıcıyı kaydeder",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Yeni kullanıcı kaydı",
                "parameters": [
                    {
                        "description": "Kullanıcı bilgileri",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/reset-password/confirm": {
            "post": {
                "description": "Kod doğruysa yeni şifre veritabanına yazılır",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Kodla şifreyi sıfırla",
                "parameters": [
                    {
                        "description": "Yeni şifre bilgileri",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ResetPasswordConfirm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/reset-password/request": {
            "post": {
                "description": "Telefon numarasına geçici şifre sıfırlama kodu üretir",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Şifre sıfırlama kodu gönder",
                "parameters": [
                    {
                        "description": "Telefon numarası",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.LoginRequest": {
            "description": "Kullanıcı giriş bilgileri",
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "description": "E-posta adresi",
                    "type": "string",
                    "example": "ahmet.yilmaz@example.com"
                },
                "password": {
                    "description": "Şifre",
                    "type": "string",
                    "minLength": 6,
                    "example": "123456"
                }
            }
        },
        "model.Polyclinic": {
            "description": "Hastane poliklinik bilgileri",
            "type": "object",
            "required": [
                "floor",
                "name",
                "room_number"
            ],
            "properties": {
                "floor": {
                    "description": "Kat numarası",
                    "type": "integer",
                    "example": 2
                },
                "name": {
                    "description": "Poliklinik adı",
                    "type": "string",
                    "example": "Kardiyoloji"
                },
                "room_number": {
                    "description": "Oda numarası",
                    "type": "integer",
                    "example": 205
                }
            }
        },
        "model.ResetPasswordConfirm": {
            "description": "Şifre sıfırlama onayı",
            "type": "object",
            "required": [
                "code",
                "confirm_password",
                "new_password",
                "phone"
            ],
            "properties": {
                "code": {
                    "description": "Doğrulama kodu",
                    "type": "string",
                    "example": "123456"
                },
                "confirm_password": {
                    "description": "Şifre tekrarı",
                    "type": "string",
                    "example": "yeni123456"
                },
                "new_password": {
                    "description": "Yeni şifre",
                    "type": "string",
                    "minLength": 6,
                    "example": "yeni123456"
                },
                "phone": {
                    "description": "Telefon numarası",
                    "type": "string",
                    "example": "05551234567"
                }
            }
        },
        "model.ResetPasswordRequest": {
            "description": "Şifre sıfırlama talebi",
            "type": "object",
            "required": [
                "phone"
            ],
            "properties": {
                "phone": {
                    "description": "Telefon numarası",
                    "type": "string",
                    "example": "05551234567"
                }
            }
        },
        "model.User": {
            "description": "Hastane kullanıcı bilgileri",
            "type": "object",
            "required": [
                "email",
                "first_name",
                "hospital_id",
                "last_name",
                "password",
                "phone",
                "role",
                "tc"
            ],
            "properties": {
                "email": {
                    "description": "E-posta adresi",
                    "type": "string",
                    "example": "ahmet.yilmaz@example.com"
                },
                "first_name": {
                    "description": "Ad",
                    "type": "string",
                    "example": "Ahmet"
                },
                "hospital_id": {
                    "description": "Hangi hastaneye ait",
                    "type": "integer",
                    "example": 1
                },
                "last_name": {
                    "description": "Soyad",
                    "type": "string",
                    "example": "Yılmaz"
                },
                "password": {
                    "description": "Şifre (JSON'dan okuyabilir ama response'da göstermez)",
                    "type": "string",
                    "minLength": 6,
                    "example": "123456"
                },
                "phone": {
                    "description": "Telefon numarası",
                    "type": "string",
                    "example": "05551234567"
                },
                "role": {
                    "description": "Rol: \"admin\" veya \"worker\"",
                    "type": "string",
                    "enum": [
                        "admin",
                        "worker"
                    ],
                    "example": "worker"
                },
                "tc": {
                    "description": "Türkiye Cumhuriyeti Kimlik Numarası",
                    "type": "string",
                    "example": "12345678901"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Hastane Takip API",
	Description:      "Bu API VatanSoft staj giriş projesi için yazılmıştır.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
